version: "3"
services:
  server:
    build: ./server
    image: heaty566/myquiz-v2-server:latest
    expose:
      - 4000

  client:
    build: ./client
    image: heaty566/myquiz-v2-client:latest
    expose:
      - 3000

  nginx:
    build: ./.docker/nginx
    image: heaty566/myquiz-v2-proxy:latest
    ports:
      - 80:80
