version: "3"
services:
        server:
                build: ./server
                image: heaty566/myquiz-v2-server:latest
                ports:
                        - 4000:4000
                env_file:
                        - ./data/config/server.env

        client:
                build: ./client
                image: heaty566/myquiz-v2-client:latest
                expose:
                        - 3000

        nginx:
                image: nginx
                ports:
                        - 80:80
